### ISSUE TITLE
Fix sidebar bugs.

### ISSUE THREAD

**Issue by Tejas-117** [BRAVO68WEB/url-minify#105]
I would like to fix the bugs in dashboard sidebar@BRAVO68WEB mentioned.

**Comment by Palak-137** [comment]
go ahead @Tejas-117

**Comment by BRAVO68WEB** [comment]
@Tejas-117 "My links" not accessible from mobile

**Comment by BRAVO68WEB** [comment]
SlideBar fixed

**Comment by BRAVO68WEB** [comment]
Make one more pr

**Comment by Tejas-117** [comment]
@BRAVO68WEB Ok, noticed it now. I will fix it.

**Comment by BRAVO68WEB** [comment]
Ok fine
