### ISSUE TITLE
Implement Light and Dark Mode

### ISSUE THREAD

**Issue by mustali17** [BRAVO68WEB/url-minify#112]
A website should be user-friendly offering both types of modes as per convenience!

**Comment by mustali17** [comment]
I want to work on this issue under GSSoC'22

**Comment by BRAVO68WEB** [comment]
Ok

**Comment by BRAVO68WEB** [comment]
Go ahead

**Comment by BRAVO68WEB** [comment]
@mustali17 Updates?

**Comment by 404-Terror** [comment]
I would like to work on it.

**Comment by Danko-chan** [comment]
Hey, I would like to work on it.

**Comment by BRAVO68WEB** [comment]
Go ahead @Danko-chan

**Comment by BRAVO68WEB** [comment]
@Danko-chan Any updates regarding both the issues

**Comment by akankshat05** [comment]
@BRAVO68WEB Can I take up this issue?
I am planning to include a button with an icon to toggle the mode in the header.
![Screenshot_12](https://user-images.githubusercontent.com/72144454/163710112-c111328f-c2ac-4c62-95ba-0dbfdfa4b04f.png)
![Screenshot_13](https://user-images.githubusercontent.com/72144454/163710118-5fc2c80a-8e08-40f2-8e96-376fdd3d8baa.png)

**Comment by BRAVO68WEB** [comment]
Sure Go ahead

**Comment by BRAVO68WEB** [comment]
@akankshat05 any progress

**Comment by akankshat05** [comment]
@BRAVO68WEB I will make a PR for it today

**Comment by BRAVO68WEB** [comment]
Great
