### ISSUE TITLE
Minify Button Disability Bug

### ISSUE THREAD

**Issue by 404-Terror** [BRAVO68WEB/url-minify#116]
**Overview**
Whenever there is no URL in the input box, on clicking the button it gets disabled(which forces users to refresh every time). Also when we click the cross button on the short url textbox, the QR Code still remains and the same happens when after having a code if we click on 'minify' using a blank url in the input box.

**Fix**
- Remove the disability function and instead add an error popup message for blank input.
- Fix the QR Code issue.

**Comment by 404-Terror** [comment]
@Palak-137 ma'am...please assign me

**Comment by BRAVO68WEB** [comment]
Its a Feature 
```Remove the disability function and instead add an error popup message for blank input.```

Don't worry about it, it their so that people can't click multiple times and create multiple minified URL for particular link.

Instead give a timeout

**Comment by BRAVO68WEB** [comment]
Go ahead @404-Terror

**Comment by 404-Terror** [comment]
> Its a Feature `Remove the disability function and instead add an error popup message for blank input.`
> 
> Don't worry about it, it their so that people can't click multiple times and create multiple minified URL for particular link.
> 
> Instead give a timeout

Okay
