### ISSUE TITLE
[UI] Adding a logo and favicon to the project.

### ISSUE THREAD

**Issue by DarkFalc0n** [BRAVO68WEB/url-minify#12]

**Comment by BRAVO68WEB** [comment]
Go ahead @DarkFalc0n

**Comment by raxvab** [comment]
I want to work with the issue under JWOC

**Comment by BRAVO68WEB** [comment]
@raxvab, The issue was created by @DarkFalc0n , so this issue is assigned to him

**Comment by raxvab** [comment]
If i create an issue would i be auto assigned?

**Comment by BRAVO68WEB** [comment]
@raxvab If you create a valid issue and I approve it
then yes.

But my approval is required

**Comment by DarkFalc0n** [comment]
I am also adding a favicon to the project with the logo

**Comment by BRAVO68WEB** [comment]
Ok
