### ISSUE TITLE
Contributors page

### ISSUE THREAD

**Issue by Palak-137** [BRAVO68WEB/url-minify#122]
Made the frontend of the contributor's page, as it an open-source helps the user to track the people who contributed to the projects.
1. design for the page is given below
2. it should be responsive
3. try to make it with the same font.

![image](https://user-images.githubusercontent.com/54790525/159134378-0d79379a-4774-4d2e-ad20-6414688bb574.png)

**Comment by Olaleye-Blessing** [comment]
Can I work on this issue?

**Comment by rakeshhotker** [comment]
@Palak-137 should this contributors page be linked to CREDITS, and i am assuming that top three contributors be displayed in the contributors page, please let me about my assumption

**Comment by BRAVO68WEB** [comment]
No @rakeshhotker, It will display all contributors

You have to make a template and we will a design page for storing those github username, pic and name.

For now make it static

**Comment by BRAVO68WEB** [comment]
Latter in #124 We will make it dynamic

**Comment by rakeshhotker** [comment]
should i link the contributors page to credits, so as to display that page when credits is clicked?

**Comment by BRAVO68WEB** [comment]
Yes

**Comment by rakeshhotker** [comment]
@BRAVO68WEB am having to rebuild the whole app after making changes to be able to see them, is there way to do hot reloading, without changing the backend, as am just following the guidelines for making changes to frontend and thus i cd'ed to frontend and working on frontend

**Comment by rakeshhotker** [comment]
@BRAVO68WEB should i hardcode the contributors or use github api to fetch and display contributors data

**Comment by BRAVO68WEB** [comment]
Hardcode

**Comment by BRAVO68WEB** [comment]
But as a function template to which we need to pass array and it automatically create cards

If you can't then also it's ok

**Comment by rakeshhotker** [comment]
@BRAVO68WEB made the contributors page following the design, the cards can be created using array.map and passing the details to the divs mentioned, although i hard coded it for now. should i create a pull request? do let me know what all i should take care of before creating a pull request

**Comment by BRAVO68WEB** [comment]
@all-contributors please add @rakeshhotker  for code
