### ISSUE TITLE
footer for the pages

### ISSUE THREAD

**Issue by Palak-137** [BRAVO68WEB/url-minify#123]
make the footer for the website, 
the design was similar to the below image and 
it should be responsive.

![image](https://user-images.githubusercontent.com/54790525/159134521-aa3e3d8a-330f-45ff-a301-6a1aa97aeaab.png)

**Comment by akankshat05** [comment]
Can I work on this?

**Comment by BRAVO68WEB** [comment]
Go ahead @akankshat05

**Comment by BRAVO68WEB** [comment]
@akankshat05 any updates?

**Comment by akankshat05** [comment]
@BRAVO68WEB I'm working on it.
