### ISSUE TITLE
integrate the github api

### ISSUE THREAD

**Issue by Palak-137** [BRAVO68WEB/url-minify#124]
To show the contributors you can implement the GitHub API to reduce the manual work.
refer to issue: #122

**Comment by himanshusanecha** [comment]
I am interested to work upon this issue.

**Comment by BRAVO68WEB** [comment]
Ok go ahead @himanshusanecha

**Comment by BRAVO68WEB** [comment]
Wait for #122

**Comment by BRAVO68WEB** [comment]
@himanshusanecha Go ahead

**Comment by himanshusanecha** [comment]
sure @BRAVO68WEB

**Comment by BRAVO68WEB** [comment]
@himanshusanecha Any updates?

**Comment by himanshusanecha** [comment]
I will complete it by tomorrow for sure. @BRAVO68WEB

**Comment by BRAVO68WEB** [comment]
@himanshusanecha Updates?

**Comment by BRAVO68WEB** [comment]
Due to inactivity
I am unassigning @himanshusanecha

**Comment by Justin-21** [comment]
I have a doubt I think the GitHub API should implement in backend or middleware .. right??
or we should directly use it in the front end??

**Comment by BRAVO68WEB** [comment]
@Justin-21 I will leave it upto you 

API reference :- https://api.github.com/repos/bravo68web/url-minify/contributors

**Comment by BRAVO68WEB** [comment]
I would suggest go for frontend implementation

**Comment by Justin-21** [comment]
Yep, now I can figure out that my task is to show this data in the front end through this API .. right??

**Comment by BRAVO68WEB** [comment]
yes

**Comment by Justin-21** [comment]
ok, thank you.
i can resolve it as soon as I can

**Comment by Olaleye-Blessing** [comment]
@BRAVO68WEB Can I work on this?

**Comment by BRAVO68WEB** [comment]
Go ahead @Olaleye-Blessing
