### ISSUE TITLE
Not enabling Minify button when another link is added after minifing first link.

### ISSUE THREAD

**Issue by Prikshit-anthal** [BRAVO68WEB/url-minify#134]
**Describe the bug**
When one link is minified, and i change link in text box . button is disabled and doesn't revert back to minify state.

**To Reproduce**
1. Go to 'Home'
2. Add any link in input box
3. Click on 'minify' button
4. Now choose anther link and change previous link.
5. Observe button is still disabled and shows minified after changing link.

**Expected behavior**
Button should revert back to minify state and get enabled when link is changed i.e onchange

**Screenshots**
![Screenshot from 2022-04-01 10-26-14](https://user-images.githubusercontent.com/79476164/161197516-623c139c-6118-437d-ab06-4874f8fdf4f6.png)

![Screenshot from 2022-04-01 10-26-07](https://user-images.githubusercontent.com/79476164/161197512-98836981-6fb7-4931-a73f-060277c9c8fb.png)

**Desktop (please complete the following information):**
 - OS: ubuntu,linux
 - Browser chrome

**Comment by Prikshit-anthal** [comment]
I am GSSoc'22 contributer kindly assign me this issue

**Comment by BRAVO68WEB** [comment]
@Prikshit-anthal That's the reason why we have a start over button

**Comment by Prikshit-anthal** [comment]
@BRAVO68WEB where is that button, i didn't see it.

**Comment by BRAVO68WEB** [comment]
![image](https://user-images.githubusercontent.com/41448663/161382655-6e51bd71-9fe3-4e28-83a1-eeaa7ccd250b.png)

**Comment by BRAVO68WEB** [comment]
@Prikshit-anthal

**Comment by Justin-21** [comment]
heyy i want to work in this issue ...
can you assign me ? 
I'm Gssoc 22 contributor

**Comment by BRAVO68WEB** [comment]
Its was never an issue
