### ISSUE TITLE
Redirect to Home page on click of logo

### ISSUE THREAD

**Issue by akankshat05** [BRAVO68WEB/url-minify#136]
**Is your feature request related to a problem? Please describe.**
Currently if we are on credits or login page, we need to click on the back button to go back to the home page. 

**Describe the solution you'd like**
Redirect to home page on click of the logo.
![Screenshot_9](https://user-images.githubusercontent.com/72144454/163723756-ef9ac5c2-cdcd-43fa-8e09-583beebefc7a.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by akankshat05** [comment]
@BRAVO68WEB can i work on this issue?

**Comment by BRAVO68WEB** [comment]
Good take @akankshat05 Go ahead

**Comment by akankshat05** [comment]
@BRAVO68WEB can you add this under GSSoC22?
