### ISSUE TITLE
URL is not minified

### ISSUE THREAD

**Issue by Olaleye-Blessing** [BRAVO68WEB/url-minify#137]
**Describe the bug**
URL is not minified when minify button is clicked.

**To Reproduce**
1. Go to [URL MiniFy](https://minfy.xyz/)
2. Input **https://dev.to/**
3. Click on minify button
4. Nothing is generated

**Expected behavior**
1. There should be a result, at least the shortened URL instead of nothing.

**Screenshots**
![Screenshot (356)](https://user-images.githubusercontent.com/70102539/163809827-8daecb17-5860-4e87-8b41-83808c31c0fb.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: **Brave**
 - Version: ---

**Additional context**
On checking the error message, I realized it was a CORS problem.

**Possible Solution**
Include https://minfy.xyz/ as part of the allowed origins. It's currently localhost

**I will be happy to work on this**

**Comment by BRAVO68WEB** [comment]
Go ahead @Olaleye-Blessing
