### ISSUE TITLE
Authentication buttons should be disabled if input fields are not filled

### ISSUE THREAD

**Issue by Olaleye-Blessing** [BRAVO68WEB/url-minify#138]
**Is your feature request related to a problem? Please describe.**
A user can currently submit button on [sign up page](https://minfy.xyz/signup) and [login page](https://minfy.xyz/login) even if no field value is provided.

**Describe the solution you'd like**
Those buttons should be disabled if all fields are not filled.

**Describe alternatives you've considered**
 ----

**Additional context**
 ------

**I would like to work on this.**

**Comment by BRAVO68WEB** [comment]
Ahhh... Ok ahead @Olaleye-Blessing
