### ISSUE TITLE
[FRONTEND] Integrated user's name shown in Dashboard

### ISSUE THREAD

**Issue by BRAVO68WEB** [BRAVO68WEB/url-minify#146]
Integrated user's name shown in Dashboard when logged in.

**Comment by Anirban-1490** [comment]
umm... assign me this . and like which area i will implement it?

**Comment by BRAVO68WEB** [comment]
Try to register and login, you will get it

**Comment by Anirban-1490** [comment]
> Try to register and login, you will get it

Here you mean ?
![Opera Snapshot_2022-04-25_154059_minfy xyz](https://user-images.githubusercontent.com/82874704/165069137-13eaf47d-3e55-4a19-8df0-4ae16bf1eeff.png)

**Comment by BRAVO68WEB** [comment]
Create a account and login

**Comment by BRAVO68WEB** [comment]
Yes

**Comment by BRAVO68WEB** [comment]
> > Try to register and login, you will get it
> 
> Here you mean ? ![Opera Snapshot_2022-04-25_154059_minfy xyz](https://user-images.githubusercontent.com/82874704/165069137-13eaf47d-3e55-4a19-8df0-4ae16bf1eeff.png)

yes

**Comment by Anirban-1490** [comment]
> > > Try to register and login, you will get it
> > 
> > 
> > Here you mean ? ![Opera Snapshot_2022-04-25_154059_minfy xyz](https://user-images.githubusercontent.com/82874704/165069137-13eaf47d-3e55-4a19-8df0-4ae16bf1eeff.png)
> 
> yes

ok

**Comment by satyam-mahajan** [comment]
@Anirban-1490 gives as try.

**Comment by Anirban-1490** [comment]
> @Anirban-1490 gives as try.

Thank you . Giving it a try

**Comment by Anirban-1490** [comment]
> @Anirban-1490 gives as try.

i want to work on it but i have a pull currently open for another issue, can you please check that so that i can work on this one ?
