### ISSUE TITLE
[FRONTED] Integrate the Dashboard tiles

### ISSUE THREAD

**Issue by BRAVO68WEB** [BRAVO68WEB/url-minify#147]
Fetch data from API to show on the Dashboard tiles.

**Comment by Anirban-1490** [comment]
can you give some more context to this. i am not understanding properly

**Comment by BRAVO68WEB** [comment]
If a user logs in he should see total views, total links created , etc expect the graph on home dashboard

**Comment by Anirban-1490** [comment]
> If a user logs in he should see total views, total links created , etc expect the graph on home dashboard

ok assign me this i will try

**Comment by Anirban-1490** [comment]
> If a user logs in he should see total views, total links created , etc expect the graph on home dashboard

can you give some more details on how the total views will work. and how the individual views will be counted?

**Comment by BRAVO68WEB** [comment]
@Anirban-1490 
total links generated :- total links generated by the logged user
for total views :- total views on that user's links

for links active :- links which was marked as active

**Comment by Anirban-1490** [comment]
> @Anirban-1490 
> total links generated :- total links generated by the logged user
> for total views :- total views on that user's links
> 
> for links active :- links which was marked as active

Ok so.
Total views is total views from all of users link that has a mail id attach( by looges user)
But for links how can i mark a link active?
And also there was another views card at the top . What should i do with it

**Comment by BRAVO68WEB** [comment]
When even a link is visited,
The view gets increased

This means the records gets updated
If you see at record got updated 3 weeks ago count as inactive.

**Comment by Anirban-1490** [comment]
> When even a link is visited, The view gets increased
> 
> This means the records gets updated If you see at record got updated 3 weeks ago count as inactive.

ok so if no views coming at max. after 3 weeks then it's inactive and then what about the view card at the top left
![Opera Snapshot_2022-04-29_133358_minfy xyz](https://user-images.githubusercontent.com/82874704/165906866-d5a34118-b26a-4a61-a0fb-cd2f4e4f182e.png)
