### ISSUE TITLE
[FRONTEND] Create a API Status Badge on the Footer of the Website

### ISSUE THREAD

**Issue by BRAVO68WEB** [BRAVO68WEB/url-minify#149]
Show a badge on the Footer about the Status of API

Fetch From :- https://caio.b68dev.xyz/checks/2.json

**Comment by akankshat05** [comment]
@BRAVO68WEB can i take up this issue?

**Comment by akankshat05** [comment]
references of badge from - https://codepen.io/jimlamb/pen/WQjByb
