### ISSUE TITLE
Unusual behaviour after user logged in

### ISSUE THREAD

**Issue by akankshat05** [BRAVO68WEB/url-minify#152]
**Describe the bug**
I have created an account using email and logged in using the same. The profile, account , dashboard, logout options are unfunctional and showing unusual behavior after it.

**Expected behavior**
Making the options functional.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: WINDOWS 11
 - Browser: mozilla firefox
 - Version 11
Video is provided below.

**Additional context**

https://user-images.githubusercontent.com/72144454/165988969-eda742c6-a53b-4077-9ca9-98f93a2f4713.mp4

**Comment by Palak-137** [comment]
Hey, those pages have not been linked with the navbar component so it's showing this behavior. if you are interested to solve go ahead.

**Comment by akankshat05** [comment]
@Palak-137 I'll work on this

**Comment by BRAVO68WEB** [comment]
@akankshat05 Any updates?

**Comment by akankshat05** [comment]
@BRAVO68WEB I'm working on it
