### ISSUE TITLE
[FRONTEND + Integration] Added Login Successful/Failure side popup

### ISSUE THREAD

**Issue by BRAVO68WEB** [BRAVO68WEB/url-minify#153]
Add the pop up show if the user's credentials are validated in login and registration page. Like "Successfully Logged In", "Successfully Registered" and "Invalid Credentials"

**Comment by BRAVO68WEB** [comment]
Case 1 according to you. Just show according to API response.

**Comment by Anirban-1490** [comment]
> Case 1 according to you. Just show according to API response.

meaning whatever error server returns i will show it ?

**Comment by BRAVO68WEB** [comment]
Yes

**Comment by Anirban-1490** [comment]
> Yes

ok assign me this i will see it

**Comment by BRAVO68WEB** [comment]
Pop up 

Check here https://short.b68dev.xyz

**Comment by Anirban-1490** [comment]
@BRAVO68WEB  This looks good ?


https://user-images.githubusercontent.com/82874704/168884811-70653a7b-d56a-42c2-ac2e-9cd81bb33b05.mp4

**Comment by BRAVO68WEB** [comment]
Yes @Anirban-1490 You doing great

**Comment by Anirban-1490** [comment]
> Yes @Anirban-1490 You doing great

👀👀👀👀
