### ISSUE TITLE
All Bottom buttons on the web-page gives 404 error

### ISSUE THREAD

**Issue by whitewalker01** [BRAVO68WEB/url-minify#156]
Bug:
Clicking on any of the buttons namely - "counter", "QR code", "Robust API", the site  takes time and loads a "404-error" page.

![image](https://user-images.githubusercontent.com/55129700/170813193-a927e55d-19fa-4a80-85df-336d6d550d85.png)

**Comment by BRAVO68WEB** [comment]
Are you willing to fix it @whitewalker01

**Comment by whitewalker01** [comment]
> Are you willing to fix it @whitewalker01
Sure, please do add tags and assign it to me.
I will be going through code and maybe I can chat on discord.

**Comment by BRAVO68WEB** [comment]
Sure
