### ISSUE TITLE
[BACKEND] Create a model to store Minified Urls

### ISSUE THREAD

**Issue by BRAVO68WEB** [BRAVO68WEB/url-minify#2]
Create a model to store all minified URLs.

**Fields**  :-
* originalUrl (required)
* minifiedAlias (required)
* views
* enable timestamps

Create `backend/models/minifed_urls.js` to store your model Schema

**Comment by dakshgupta2002** [comment]
Interested!

**Comment by BRAVO68WEB** [comment]
Noted. Will be assigned on 1st Feb

**Comment by unnikrishnan2002** [comment]
I want to work on this issue under JWOC

**Comment by BRAVO68WEB** [comment]
@dakshgupta2002 Go ahead

**Comment by chirag3003** [comment]
I want to work on this issue under JWOC

**Comment by BRAVO68WEB** [comment]
Closeing issue

**Comment by chirag3003** [comment]
Bug Report:
The support for using import export is not enabled in this backend
you have to use require.
The backend is not compiling

**Comment by BRAVO68WEB** [comment]
@chirag3003 fix and pr
