### ISSUE TITLE
[FRONTEND] Design a Text Box and Submit button

### ISSUE THREAD

**Issue by BRAVO68WEB** [BRAVO68WEB/url-minify#22]
Add a Text Box and Submit button as shown in the preview

Here :- ![UI](https://user-images.githubusercontent.com/41448663/151844736-29d6ed58-6fc5-4114-8912-3a53e4ee6504.png)

**Comment by aaheli8** [comment]
I want to work on this issue under JWOC

**Comment by BRAVO68WEB** [comment]
Go ahead @aaheli8
