### ISSUE TITLE
[FRONTEND] Add a UI Component to show Features under the Text Box and Submit Button

### ISSUE THREAD

**Issue by BRAVO68WEB** [BRAVO68WEB/url-minify#23]
Here :- ![UI](https://user-images.githubusercontent.com/41448663/151844727-d85df415-4a8e-4d2b-a695-59e5edfb370f.png)

**Comment by dakshgupta2002** [comment]
Can i be assigned to this issue?

**Comment by BRAVO68WEB** [comment]
@dakshgupta2002
