### ISSUE TITLE
[FRONTEND] Setup axios instances

### ISSUE THREAD

**Issue by chirag3003** [BRAVO68WEB/url-minify#25]

**Comment by chirag3003** [comment]
set Axios instances for API integration so that we don't have write the whole config everytime when calling the api

**Comment by BRAVO68WEB** [comment]
@chirag3003 Go ahead

**Comment by chirag3003** [comment]
Pls reassign this issue to me

**Comment by BRAVO68WEB** [comment]
Ok I have reassigned @chirag3003

**Comment by BRAVO68WEB** [comment]
@chirag3003 When will you PR?

**Comment by BRAVO68WEB** [comment]
@chirag3003 What's the progress?

**Comment by harshit-070** [comment]
I want to work on this issue under JWOC
