### ISSUE TITLE
[FRONTEND] Create Basic Dashboard for Users

### ISSUE THREAD

**Issue by BRAVO68WEB** [BRAVO68WEB/url-minify#36]
Create a Basic Dashboard for Logged-in users

Reference:- 
![Overview Page](https://user-images.githubusercontent.com/41448663/152535786-394a70f7-f429-4b25-b96e-017a0412619d.png)

This UI is bound to change with modern UI soon. So, only make skeleton

**Comment by logan4473** [comment]
I want to work on this issue under JWOC.

**Comment by BRAVO68WEB** [comment]
A Team of 3 Require for this

2 people: Basic UI 
1. person Graphs

**Comment by BRAVO68WEB** [comment]
@logan4473 Wait for sometime 

I will assign this to 3 people

**Comment by BRAVO68WEB** [comment]
I am waiting for others to comment

**Comment by logan4473** [comment]
Got it

**Comment by chirag3003** [comment]
I want to work on this issue under JWOC.

**Comment by chirag3003** [comment]
I would like to work on graphs

**Comment by BRAVO68WEB** [comment]
Got 2

**Comment by BRAVO68WEB** [comment]
One more

**Comment by logan4473** [comment]
I would like to work on Menus and Button

**Comment by BRAVO68WEB** [comment]
@chirag3003 @logan4473 New UI is here
![Overview UI](https://user-images.githubusercontent.com/41448663/152674005-247ef869-a034-4005-9cc3-dfa3d4477718.png)

**Comment by aaheli8** [comment]
Can I work on this issue?

**Comment by BRAVO68WEB** [comment]
Yes Sure

**Comment by BRAVO68WEB** [comment]
@aaheli8 @chirag3003 @logan4473 What's the progress?

**Comment by aaheli8** [comment]
@BRAVO68WEB I have to make the basic UI layout?

**Comment by BRAVO68WEB** [comment]
@aaheli8 Discuss with the other two

**Comment by chirag3003** [comment]
@BRAVO68WEB sorry for taking so much time I was busy with my exams I will make a pr today
