### ISSUE TITLE
[BACKEND + INTEGRATION]  Increase View counts when visited

### ISSUE THREAD

**Issue by BRAVO68WEB** [BRAVO68WEB/url-minify#39]
Increase View by one when ever someone visits a minified URL.

**Comment by ronitblenz** [comment]
I want to work on this issue

**Comment by BRAVO68WEB** [comment]
Ok @ronitblenz

**Comment by ronitblenz** [comment]
I cant do this, I thought it had HTML,CSS
I dont have knowledge regarding JS Frameworks.
I really apologise
Hope so, Someone can solve this issue, thats why I am unassigning myself

Thanks for understanding and sorry again

**Comment by harshit-070** [comment]
I want to work on this issue under JWOC

**Comment by BRAVO68WEB** [comment]
Go ahead

**Comment by BRAVO68WEB** [comment]
But await wait till #38

**Comment by XxThunderBlastxX** [comment]
i want to work on this issue under JWOC

**Comment by hazemessam** [comment]
I want to solve this issue under GSSoC 22.

**Comment by BRAVO68WEB** [comment]
@hazemessam Right now we are participating in JWOC

**Comment by hazemessam** [comment]
Ok, I already worked on it and added this feature to the backend. If this issue is not solved after a while, you can assign it to me to make a PR.

**Comment by BRAVO68WEB** [comment]
Sure But I will only accepts PRs after 1 Mar or else its considered as Open Source Contribution not for GSSoC

**Comment by hazemessam** [comment]
Ok, I will make a PR on 1 Mar.

**Comment by Gurdeep475** [comment]
I would like to work on this issue under GSSOC`22.

**Comment by hazemessam** [comment]
@BRAVO68WEB,  I think you can assign it to me now under GSSoC'22

**Comment by BRAVO68WEB** [comment]
@hazemessam He did it.
