### ISSUE TITLE
[BACKEND] Delete data from Database via /minify/delete/:id route

### ISSUE THREAD

**Issue by BRAVO68WEB** [BRAVO68WEB/url-minify#4]
Create DELETE at /minify/delete/:id to take MongoDB Field id as input via parameter, and delete them from the database.

**Comment by XxThunderBlastxX** [comment]
@BRAVO68WEB I am interested to do this issue , can you assign this issue to me ??

**Comment by BRAVO68WEB** [comment]
Yeah, sure I will keep that in mind

**Comment by chirag3003** [comment]
I want to work on this issue under JWOC

**Comment by XxThunderBlastxX** [comment]
I want to work on this issue under JWOC
