### ISSUE TITLE
[INTEGRATION] Generate a new minified URL

### ISSUE THREAD

**Issue by BRAVO68WEB** [BRAVO68WEB/url-minify#40]
When ever a user enters a new URL, make a request to backend to Create a short code and return the entire minified URL as well as copy the same to clip board

**Comment by dakshgupta2002** [comment]
Interested in this...

**Comment by BRAVO68WEB** [comment]
Ok @dakshgupta2002

**Comment by dakshgupta2002** [comment]
Merged

**Comment by BRAVO68WEB** [comment]
Add @dakshgupta2002 as a contributor for code.
