### ISSUE TITLE
[BACKEND] Generate a QR code for the minified url

### ISSUE THREAD

**Issue by Lunatix01** [BRAVO68WEB/url-minify#41]
Hello i want to implement a feature like that for it

**Comment by BRAVO68WEB** [comment]
@Lunatix01 Backend?

**Comment by BRAVO68WEB** [comment]
Ok then, sure no issues

This issue is opened for you to claim

But not now. Let the existing issues close

**Comment by Lunatix01** [comment]
well it can be implemented in the front end too, i think the front end is much easier so no need to store the qr code, i will claim it
i will wait till the existing issues close
