### ISSUE TITLE
[BACKEND] List all minified URLs from Database to /minify/all route 

### ISSUE THREAD

**Issue by BRAVO68WEB** [BRAVO68WEB/url-minify#5]
Create GET route at /minify/all to list all URLs, minified Alias as JSON from the database.

**Comment by luxunator** [comment]
I would like to be assigned this issue on Feb 1st if possible.

**Comment by chirag3003** [comment]
I am interested

**Comment by chirag3003** [comment]
I want to work on this issue under JWOC

**Comment by BRAVO68WEB** [comment]
@luxunator Go ahead

**Comment by BRAVO68WEB** [comment]
@luxunator Any updates on the issue?
