### ISSUE TITLE
[INTEGRATION] Integrate Login Form for users to login

### ISSUE THREAD

**Issue by BRAVO68WEB** [BRAVO68WEB/url-minify#62]
Wait for completion of #34

**Comment by BRAVO68WEB** [comment]
@03amir Do ahead

**Comment by DarkFalc0n** [comment]
I want to work on this issue under JWOC

**Comment by BRAVO68WEB** [comment]
Go ahead @DarkFalc0n

**Comment by Gurdeep475** [comment]
i would like to contribute on this issue under GSSOC`22

**Comment by BRAVO68WEB** [comment]
@Gurdeep475 Assigning it to you

**Comment by Gurdeep475** [comment]
Thanks. I am working on it.

**Comment by BRAVO68WEB** [comment]
@Gurdeep475 What's your progress?

**Comment by Gurdeep475** [comment]
Sorry, I got busy up with college work, I will start working from today. @BRAVO68WEB can you given some guidance on what needs to be done, the backend part seems to be already having other required routes and controllers.

**Comment by BRAVO68WEB** [comment]
You need to have authentication integrated with frontend so respected users can login to dashboard with their email and password 

@Gurdeep475

**Comment by BRAVO68WEB** [comment]
@Gurdeep475 any updates?

**Comment by Tejas-117** [comment]
@BRAVO68WEB I would like to work on this under GSSOC 2022.

**Comment by BRAVO68WEB** [comment]
@Tejas-117 go ahead

**Comment by BRAVO68WEB** [comment]
@Tejas-117 Any progress?

**Comment by Tejas-117** [comment]
@BRAVO68WEB Yes, I implemented front end part of posting, showing message etc.
I will complete backend aspects soon.

**Comment by BRAVO68WEB** [comment]
Ok

**Comment by BRAVO68WEB** [comment]
@Tejas-117 Any updates?

If not then I will work on this. Its Ok if you can't

**Comment by chirag3003** [comment]
@BRAVO68WEB assign it to me
