### ISSUE TITLE
[FRONTEND] Create Link page for Logged In users in dashboard

### ISSUE THREAD

**Issue by BRAVO68WEB** [BRAVO68WEB/url-minify#63]
Reference :-
![Create Link Page](https://user-images.githubusercontent.com/41448663/154072021-d9ceec0b-faf9-4ae4-bb4c-f14eb2f95f00.png)

**Comment by 03amir** [comment]
i want to work on this issue under jwoc

**Comment by BRAVO68WEB** [comment]
ok
