### ISSUE TITLE
[FRONTEND] Add Functionality to View All Links created by a User

### ISSUE THREAD

**Issue by BRAVO68WEB** [BRAVO68WEB/url-minify#72]
Design :- 
![My links](https://user-images.githubusercontent.com/41448663/156037536-c9ca4acd-f93b-412f-a6e1-ca5a225c244f.png)

Do's :- 
Create Demo Items and add 5 demo items as links

Don'ts :- 
Don't integrate with Backend

**Comment by hazemessam** [comment]
I want to work on this issue under GSSoC'22

**Comment by BRAVO68WEB** [comment]
Ok go ahead

**Comment by hazemessam** [comment]
I'm sorry I didn't notice that it is a frontend task.

**Comment by hazemessam** [comment]
please unassign me and reassign me to this issue #74

**Comment by BRAVO68WEB** [comment]
@hazemessam That's also Frontend + Integration

**Comment by BRAVO68WEB** [comment]
I will create more Backend Issues tomorrow, you may take those

**Comment by aadityasinha-dotcom** [comment]
Is this available?
Can I work on this issue under GSSOC'22?

**Comment by BRAVO68WEB** [comment]
Yes Go ahead

**Comment by BRAVO68WEB** [comment]
@aadityasinha-dotcom What's your progress?

**Comment by aadityasinha-dotcom** [comment]
Almost done.

![Screenshot from 2022-03-05 16-38-44](https://user-images.githubusercontent.com/75474786/156880570-0a9ffd56-09e0-49b8-b7e2-5e5b628c87f8.png)

**Comment by BRAVO68WEB** [comment]
Ok

**Comment by BRAVO68WEB** [comment]
@aadityasinha-dotcom Have you button to open this menu?

From left side in nav menu

**Comment by aadityasinha-dotcom** [comment]
Yes

**Comment by BRAVO68WEB** [comment]
How to open it?

**Comment by aadityasinha-dotcom** [comment]
> How to open it?

/myLinks
