### ISSUE TITLE
Enhance the documentation 

### ISSUE THREAD

**Issue by Palak-137** [BRAVO68WEB/url-minify#77]
Currently, the documentation was not that clear for anyone coming for the first time to the repo. You can use your writing skills to enhance the documentation of the project, like writing elaborated readme.
It can be funky and should help the readers to learn more about the project.

**Comment by Debajyoti14** [comment]
I would like to update the documentation
Please assign it to me

**Comment by BRAVO68WEB** [comment]
What's your progress? @Debajyoti14
