### ISSUE TITLE
Fix the broken UI page after minifying the URL

### ISSUE THREAD

**Issue by Palak-137** [BRAVO68WEB/url-minify#78]
When we minify the URL you are automatically directed to the 404 page. Although the backend is returning the minify URL it still won't show it. we need proper UI to fix that. 

**Expected behavior**
 After minifying the URL and QR code with good UI

**Comment by Rajdip019** [comment]
Hey, Can I work on this?

**Comment by BRAVO68WEB** [comment]
@Palak-137 Fixed
