### ISSUE TITLE
Integrating the link page for the logged in user.

### ISSUE THREAD

**Issue by Palak-137** [BRAVO68WEB/url-minify#79]
A user who is already logged in should be able to make access the custom link page where he can add a custom alias for the URL. the page is already built we just need to integrate it with the current application. 

This will help the user to access the various feature after logging in only.

**Comment by himanshusanecha** [comment]
If this issue is still available, I can work upon it.

Some insights on how it will be implemented - 
1. Creating a page of alias management (frontend) - where user can create, delete or read alias.
2. Creating api's to manage aliases of a user.
3. While a user is minifying a URL - he/she can select the aliases from his/her list.
4. While user is adding a URL we will check if the alias has been selected or not.
       - If alias is present - use that alias.
       - else generate an alias and save the URL.

**Comment by BRAVO68WEB** [comment]
@himanshusanecha This one just for linking/integration

Check #67 > Here the link page is already created.

Are you willing to integrate.

**Comment by Devmindtk** [comment]
I would like to work on this issue under GSSoc 22 .please assign it to me

**Comment by BRAVO68WEB** [comment]
Go ahead @Devmindtk

**Comment by Devmindtk** [comment]
> Go ahead @Devmindtk

could you please help me I am not able to run it into my localhost

**Comment by BRAVO68WEB** [comment]
@Devmindtk 
Clone the Repo and follow here
https://github.com/BRAVO68WEB/url-minify/blob/main/HOW_TO_CONTRIBUTE.md#for-front-end

**Comment by BRAVO68WEB** [comment]
@Devmindtk What's your progress?

**Comment by Devmindtk** [comment]
> @Devmindtk What's your progress?

I know the solution of issue but facing issue to run this project on my localhost.

**Comment by BRAVO68WEB** [comment]
@Devmindtk What is the issue? 

Make sure you configure .env in order to run the project.

**Comment by aadityasinha-dotcom** [comment]
Can I work on this issue?

**Comment by BRAVO68WEB** [comment]
@Devmindtk any updates?

**Comment by Devmindtk** [comment]
Yeah try to solve will update you by today

**Comment by aadityasinha-dotcom** [comment]
@Devmindtk If you got any query/problem you can discuss it on discord.

**Comment by BRAVO68WEB** [comment]
@aadityasinha-dotcom any updates

**Comment by aadityasinha-dotcom** [comment]
> @aadityasinha-dotcom any updates

Can you tell me what changes have been made to the login page?

**Comment by BRAVO68WEB** [comment]
You just need to do this.

When ever someone clicks on Create Link from Dashboard, open the Page and integrated it with backend.

When the user is setting his custom, make a get request simultaneously to check weather it is available or not.
If available show below the text box in green color that "Alias is available" or in red "Alias is not available"

**Comment by BRAVO68WEB** [comment]
> You just need to do this.
> 
> When ever someone clicks on Create Link from Dashboard, open the Page and integrated it with backend.
> 
> When the user is setting his custom, make a get request simultaneously to check weather it is available or not. If available show below the text box in green color that "Alias is available" or in red "Alias is not available"

@aadityasinha-dotcom

**Comment by BRAVO68WEB** [comment]
Page component is already created only integration left

**Comment by aadityasinha-dotcom** [comment]
Okay, got it.

**Comment by BRAVO68WEB** [comment]
@Palak-137 or @satyam-mahajan Can you fix this?

**Comment by rakeshhotker** [comment]
is this issue still open?

**Comment by BRAVO68WEB** [comment]
Yes
