### ISSUE TITLE
Make all pages responsive.

### ISSUE THREAD

**Issue by Tejas-117** [BRAVO68WEB/url-minify#81]
**Describe the bug**
The pages doesn't scale well for mobile devices.

![Screenshot](https://user-images.githubusercontent.com/75026048/156207869-8a3a29d5-a6c1-4a33-b6d6-ee30fa714275.png)

I would like to work on this issue under GSSOC 2022.

**Comment by BRAVO68WEB** [comment]
Go ahead

**Comment by BRAVO68WEB** [comment]
Make sure sure to make all pages responsive

**Comment by Tejas-117** [comment]
Thanks I am working on it.
