### ISSUE TITLE
Typography and UI

### ISSUE THREAD

**Issue by Sakshi-Gupta06** [BRAVO68WEB/url-minify#82]
all the fonts are the same, it looks bad and unclear to user.
and UI of footer also
I want to work in this 

please assign me

**Comment by BRAVO68WEB** [comment]
@Palak-137

**Comment by Palak-137** [comment]
@Sakshi-Gupta06  you can proceed! happy to help

**Comment by 404-Terror** [comment]
I want to improve the home page UI and also looking to add some small animations using framer-motion.

Please assign me.

**Comment by BRAVO68WEB** [comment]
@Sakshi-Gupta06 What's your progress?

**Comment by BRAVO68WEB** [comment]
No updates revieved
