### ISSUE TITLE
[Backend] Blacklist some alias from being create

### ISSUE THREAD

**Issue by BRAVO68WEB** [BRAVO68WEB/url-minify#83]
Ban custom alias keywords like the following :- 
  * 404
  * dashboard
  * qr
  * credits
  * github
  * admin
  * geo
  * all
  * me
  * go
  * upload
  * download
  * link
  * about
  * tos
  * faqs
 
 No one should be able to create backend aliases with these key words, while creating custom aliases

**Comment by himanshusanecha** [comment]
I am interested to work on this issue.
