### ISSUE TITLE
[BACKEND] Prevent duplicate alias creation

### ISSUE THREAD

**Issue by BRAVO68WEB** [BRAVO68WEB/url-minify#84]
Prevent create creation of duplicate alias creating.

Approach :- 
1. For /minify/add :- Check database if auto generated alias if present or not. If present regenerate.
2. For /minify/add/custom :- Add an additional endpoint /minify/alias/:alias/status 
                     Here check in database if already present, if yes return {"success": "false"} else  {"success": "true"}

**Comment by BRAVO68WEB** [comment]
@Nanzzie What's your progress?

**Comment by BRAVO68WEB** [comment]
@Nanzzie Any progress?

**Comment by BRAVO68WEB** [comment]
Or shall I assign?

**Comment by Nanzzie** [comment]
Yess sir u can unassign it

**Comment by Danko-chan** [comment]
is it still unresolved? If yes, then i would like to try.

**Comment by BRAVO68WEB** [comment]
@Danko-chan PR under review. Lets See

You may create Issues if you want to contribute

**Comment by BRAVO68WEB** [comment]
@Danko-chan Go ahead
