### ISSUE TITLE
UI fix and font-size

### ISSUE THREAD

**Issue by Faraaz2633** [BRAVO68WEB/url-minify#89]
Hey there,
On the main page, there is an extra margin at the bottom and the login button size is also not correct,
I would like to work on this issue.
could you please assign it to me under GSSoC and JWOC?

**Comment by BRAVO68WEB** [comment]
already assigned #82

**Comment by Faraaz2633** [comment]
> already assigned #82

But Level one / Easy issue should not take more than one day right?

**Comment by BRAVO68WEB** [comment]
@Faraaz2633 Its not JWOC and also I don't enforce rules as they are here to learn.
